
/* Generated by Interface Builder */

#import "CodeView.h"

@implementation CodeView

- initFrame:(const NXRect *)frameRect
{
    [super initFrame:frameRect];
	[self setHorizScrollerRequired:YES];
	[theText setHorizResizable:YES];
	[theText setNoWrap];
	[theText setEditable:NO];
	return self;
}


@end
