
/* Generated by Interface Builder */

#import "ConsoleText.h"
#import "KeyQueue.h"

@implementation ConsoleText

- keyDown:(NXEvent *)theEvent {
	if (theEvent->type != NX_KEYDOWN) return self;
	if (theEvent->data.key.charSet == NX_ASCIISET) {
		switch (theEvent->data.key.charCode) {
			case 0x08:
			case 0x7f:
				[keyBuffer deleteChar];
				break;
			case 0x03:
			case 0x0D:
				[keyBuffer addChar:'\n'];
				break;
			default:
				if (theEvent->data.key.charCode >= 0x20)
					[keyBuffer addChar:theEvent->data.key.charCode];
				break;
		}
		[self setSel:textLength:textLength];		
		return [super keyDown:theEvent];
	}
	return self;	
}

- setBuffer:kq {
	keyBuffer = kq;
	return self;
}

@end
