
/* Generated by Interface Builder */

#import "ConsoleView.h"
#import "ConsoleText.h"
#import "KeyQueue.h"

@implementation ConsoleView

- newText:(const NXRect *)frameRect
{
    id	text;
    NXSize aSize = {1.0E38, 1.0E38};
    
    text = [[ConsoleText alloc] initFrame:frameRect
    			 text:NULL
			 alignment:NX_LEFTALIGNED];
    [text setOpaque:YES];
    [[[[[text notifyAncestorWhenFrameChanged:YES]
				setVertResizable:YES]
				    setHorizResizable:NO]
					setMonoFont:YES]
					    setDelegate:self];
    
    [text setMinSize:&(frameRect->size)];
    [text setMaxSize:&aSize];
    [text setAutosizing:NX_HEIGHTSIZABLE | NX_WIDTHSIZABLE];
    
    [text setCharFilter:NXEditorFilter];
    
	kq = [KeyQueue alloc];
	[kq init];
	[text setBuffer:kq];
	return text;
}

- queue {
	return kq;
}

@end
