#
# Generated by the NeXT Interface Builder.
#
# NOTE: Do NOT change this file -- Interface Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = NeXTspim

INTERFACES = NeXTspim.nib
CLASSES = BreakpointsPanel.m CodeView.m ConsoleText.m ConsoleView.m \
          ContinuePanel.m KeyQueue.m PrefsPanel.m SPIMInterface.m \
          StatsWindow.m TextView.m
MFILES = NeXTspim_main.m RunLoop.m
CFILES = cl-cache.c cl-cycle.c cl-except.c cl-tlb.c data.c inst.c lex.yy.c \
         mem.c mips-syscall.c read-aout.c run.c spim-utils.c sym-tbl.c \
         y.tab.c
HFILES = RunLoop.h cl-cache.h cl-cycle.h cl-except.h cl-mem.h cl-tlb.h \
         data.h inst.h mem.h mips-syscall.h op.h parser.h read-aout.h \
         reg.h run.h scanner.h spim-syscall.h spim-utils.h spim.h \
         sym-tbl.h y.tab.h
OTHERSRCS = trap.handler
APPICON = spim.tiff


SOURCEMODE = 444

LIBS = -lNeXT_s -lsys_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = -lNeXT_p -lsys_p

MAKEFILEDIR = /usr/lib/nib
ICONSECTIONS =	-sectcreate __ICON app spim.tiff
APPWRAPPER = YES
NOMACHO = YES

INSTALLDIR = $(HOME)/tmp
INSTALLFLAGS = -c -s -m 755

-include Makefile.preamble

include $(MAKEFILEDIR)/app.make

-include Makefile.postamble

-include Makefile.dependencies
